### PR TITLE
Update connect-spam-node doc

### PR DESCRIPTION
**Pull request by stubbsta**
This PR adds documentation which describes how to connect a spamming node

### CODE REVIEW

**Review by alrevuelta — APPROVED** [review]
lgtm

Perhaps a more realistic test could be using discv5 instead of a hardcoded `staticnode`. But both tests can be interesting.

**Comment by stubbsta** [comment]
> lgtm
> 
> Perhaps a more realistic test could be using discv5 instead of a hardcoded `staticnode`. But both tests can be interesting.

Shall I add a section in the document with the required discv5 config to show that it is an option?

**Comment by alrevuelta** [comment]
> Shall I add a section in the document with the required discv5 config to show that it is an option?

would be nice yeap. just the command (using discv5) after the one we already have with some explanation is fine.

**Comment by stubbsta** [comment]
Discv5 config included in https://github.com/waku-org/waku-simulator/pull/75/commits/7038df710dffdb5b6b9ec0d4582e632a927b8960

**Review by alrevuelta — APPROVED** [review]

**Pull request merged**
