### PR TITLE
Remove support for gowaku

### PR DESCRIPTION
**Pull request by stubbsta**
* Remove support for go-waku.
* closes https://github.com/waku-org/waku-simulator/issues/26.

### CODE REVIEW

**Comment by alrevuelta** [comment]
The diff doesn't look right, @stubbsta can you rebase?

**Review by alrevuelta — CHANGES_REQUESTED** [review]
The diff doesn't look right, @stubbsta can you rebase?

**Comment by stubbsta** [comment]
My first attempt at rebasing doesn't seem to have worked, I'm working on it

**Review by alrevuelta — APPROVED** [review]
lgtm!

**Pull request merged**
